# Generated by Django 6.0.5 on 2026-06-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EEJTPStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wwid_pathway_coursename', models.TextField(blank=True, default='')),
                ('wwid_pathway', models.TextField(blank=True, default='')),
                ('pathway_coursename', models.TextField(blank=True, default='')),
                ('employee_wwid', models.TextField(blank=True, default='')),
                ('employee_name', models.TextField(blank=True, default='')),
                ('employee_email', models.TextField(blank=True, default='')),
                ('is_manager', models.TextField(blank=True, default='')),
                ('mgr_name', models.TextField(blank=True, default='')),
                ('mgr_email', models.TextField(blank=True, default='')),
                ('mgr_wwid', models.TextField(blank=True, default='')),
                ('org_unit_descr', models.TextField(blank=True, default='')),
                ('org_level_desc7', models.TextField(blank=True, default='')),
                ('assigned_pathway', models.TextField(blank=True, default='')),
                ('assigned_date', models.TextField(blank=True, default='')),
                ('due_date', models.TextField(blank=True, null=True)),
                ('course_name', models.TextField(blank=True, default='')),
                ('course_id', models.FloatField(blank=True, null=True)),
                ('course_type', models.TextField(blank=True, default='WBT')),
                ('status', models.TextField(blank=True, null=True)),
                ('refresh_date', models.TextField(blank=True, null=True)),
                ('manually_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"EE_JTP_Status"',
                'ordering': ['employee_name', 'assigned_pathway', 'course_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JTPPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway_coursename', models.TextField(blank=True, default='')),
                ('pathway_name', models.TextField(blank=True, default='')),
                ('course_name', models.TextField(blank=True, default='')),
                ('course_id', models.BigIntegerField(blank=True, null=True)),
                ('course_type', models.TextField(choices=[('ILT', 'ILT'), ('WBT', 'WBT'), ('Other', 'Other')], default='WBT')),
                ('expect_completion_time', models.BigIntegerField(blank=True, choices=[(90, '3 Months'), (180, '6 Months'), (360, '1 Year')], default=90, null=True)),
                ('refresh_cycle', models.BigIntegerField(blank=True, choices=[(90, '3 Months'), (180, '6 Months'), (360, '1 Year')], null=True)),
                ('owner_wwid', models.TextField(blank=True, db_column='owner', default='')),
                ('material', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"JTP_Pathways"',
                'ordering': ['pathway_name', 'course_name'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='jtpteammember',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jtpteammember',
            name='mgr_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jtpteammember',
            name='module',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jtpteammember',
            name='org_level_desc7',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jtpteammember',
            name='org_unit_descr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jtpteammember',
            name='role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jtpteammember',
            name='source',
            field=models.CharField(default='org', max_length=10),
        ),
    ]
