# Generated by Django 6.0.5 on 2026-06-25 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jtp', '0002_add_ee_fields_to_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jtpteammember',
            name='is_excluded',
        ),
        migrations.RemoveField(
            model_name='jtpteammember',
            name='source',
        ),
    ]
