# Generated by Django 6.0.5 on 2026-06-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtp', '0003_remove_source_is_excluded_from_team_members'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jtpteammember',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='jtpteammember',
            name='employee_wwid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
