# Generated by Django 6.0.5 on 2026-06-25 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jtp', '0004_employee_wwid_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jtpteammember',
            name='created_at',
        ),
    ]
